pipeline {
    agent { label "agent-one" }

    environment {
        DOCKERHUB_USER = "vjstylose"
        IMAGE_NAME = "online_shopping_web"
        IMAGE_TAG = "latest"
        COMPOSE_FILE = "config/docker-compose.yml"
    }

    stages {
        stage("Checkout Code") {
            steps {
                echo "Cloning project..."
                deleteDir()
                git url: 'https://github.com/vivekjhariya/online-shop-eb.git', branch: 'main'
            }
        }

        stage("Pre-Build Cleanup") {
            steps {
                echo "Removing old containers and images..."
                sh '''
                    # Stop & remove container
                    docker ps -aq --filter "name=$IMAGE_NAME" | xargs -r docker stop || true
                    docker ps -aq --filter "name=$IMAGE_NAME" | xargs -r docker rm || true

                    # Remove images
                    docker images -q $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG | xargs -r docker rmi -f || true
                    docker images -q $IMAGE_NAME:$IMAGE_TAG | xargs -r docker rmi -f || true

                    # Remove dangling images
                    docker image prune -f || true
                '''
            }
        }

        stage("Run Tests") {
            steps {
                echo "Running tests inside Docker build (test stage)..."
                sh '''
                    docker build --target test -f config/Dockerfile -t $IMAGE_NAME:test .
                '''
                echo "Tests passed (no errors)"
            }
        }

        stage("Build Docker Image") {
            steps {
                echo "Building Docker image..."
                sh '''
                    docker build -f config/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
                    docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
                '''
                echo "Image tagged as $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG"
            }
        }

        stage("Push to DockerHub") {
            steps {
                echo "☁️ Pushing image to DockerHub..."
                withCredentials([usernamePassword(credentialsId: 'dockerhubcred', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                        echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                        docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
                        docker logout
                    '''
                }
            }
        }

        stage("Deploy via Docker Compose") {
            steps {
                echo " Deploying via Docker Compose...."
                sh '''
                    docker-compose -f $COMPOSE_FILE pull
                    docker-compose -f $COMPOSE_FILE up -d --remove-orphans
                '''
                echo "Deployment complete!"
            }
        }
    }
}
